### ISSUE TITLE
preview window can't scroll properly

### ISSUE THREAD

**Issue by younger-1** [hrsh7th/nvim-deck#8]
Open the preview window with `p`, but `<C-u>`/`<C-d>` can't scroll the window. I have followed the setup config in readme.

**Comment by hrsh7th** [comment]
hm... Could you try the following check?

1. Open deck window
2. Open preview window
3. `:nnoremap <C-d>`

**Comment by younger-1** [comment]
after `:nnoremap <C-d>` in deck window, msg show is

```
n  <C-D>       *@<Lua 933: ~/.local/share/lazy/lazy/nvim-deck/lua/deck/Context.lua:843>
                 deck.action
```

**Comment by hrsh7th** [comment]
Hm... I can't reproduce with [this](https://github.com/hrsh7th/nvim-deck/blob/main/misc/init.lua) configuration.

**Comment by younger-1** [comment]
The misc configuration also works well on my end. Finally, I found that the root cause of the issue is `set scrolloff=4` in my configuration. Once `scrolloff` set to 0, the preview window scroll properly

**Comment by hrsh7th** [comment]
Thank you! I'll fix it on nvim-deck side.

**Comment by younger-1** [comment]
sorry, i pull the latest commits, but still can't scroll

**Comment by younger-1** [comment]
I somehow enter the preview window, and found these window-local options' value is not what should be set.
https://github.com/hrsh7th/nvim-deck/blob/65cc149649bade89ab4fe27bf35e230c855984b2/lua/deck/builtin/view/default.lua#L217-L224

**Comment by hrsh7th** [comment]
IMO, these options should be set. Could you explain why do you think these options shouldn't be set?

**Comment by younger-1** [comment]
Oh, I mean these options should be set, but actually somehow they are not be set.

As shown below based on misc configuration, `number` option is not set.
![image](https://github.com/user-attachments/assets/5fb79c8c-6516-485b-94c1-a5745015b799)

**Comment by hrsh7th** [comment]
As you said, it seems the window options were not being set 😅 
Fixed!

**Comment by younger-1** [comment]
Thanks!
